### ISSUE TITLE
Document all current Helpers

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-communitytoolkit#10]
Write Docs for all the Helpers that are currently available. You can find them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Helpers).

- [x] DelegateWeakEventManager
- [ ] LocalizationResourceManager
- [ ] Subscription
- [x] WeakEventManager<T>

**Comment by sthewissen** [comment]
Not sure if `SafeArea.shared` and `SafeAreaTypeConverter` need separate docs. They are internals for the `SafeAreaEffect` which is documented.

**Comment by jfversluis** [comment]
I thought I left those out 😅 done, thanks!

**Comment by Cfun1** [comment]
@jfversluis the link of "Here" "https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Helpers" is not working. Some refactoring happened since that time maybe, needs to be replaced with https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers ?

**Comment by brminnick** [comment]
@jfversluis `WeakEventManagerService` doesn't need documentation because it is an internal class, not a public class: 	https://github.com/xamarin/XamarinCommunityToolkit/blob/fa93de144580352db2a2c766685410d6b77d0da1/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/WeakEventManagerService.shared.cs#L11

**Comment by jfversluis** [comment]
Progress without required effort, love it!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).
